package com.hack.TransmissionLineService;

public enum Action {
	NO_PENDING_ACTION, 
	APPLY_CONSTRAINT, 
	ACCEPT_DISPATCH, 
	SEND_DISPATCH, 
	UPDATE_CONSTRAINT, 
	RECOMMEND_CONSTRAINT,
	CHECK_FLOW_ON_LINE,
	GET_POOL_PRICE;
}
